[package]
name = "pwned_check"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.2"
colored = "2.0"
rs-password-utils = "0.1"
tokio = {version = "0.2.25", features = ["macros"]}